version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2019
- Ubuntu

configuration:
- Debug
- Mixed
- Release
- Release Master Gold

platform:
- x64
- x86

branches:
  except:
    - dependabot/*

matrix:
  exclude:
    - image: Ubuntu
      configuration: Mixed
    - image: Ubuntu
      configuration: Release Master Gold

cache:
- src/packages -> **/packages.config

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  before_build:
    - git submodule update --init --recursive
    - nuget restore src\engine.sln
  build:
    project: src/engine.sln
    parallel: true
    verbosity: minimal
  after_build:
    - cmd: xr_pack_build.cmd
  artifacts:
    - path: res/OpenXRay.*.7z
      name: OpenXRay.*.7z
    - path: res/Symbols.*.7z
      name: Symbols.*.7z
    - path: res/Utils.*.7z
      name: Utils.*.7z
-
  matrix:
    only:
      - image: Ubuntu
  before_build:
    - git submodule update --init --recursive
    - git submodule deinit Externals/cryptopp
  build_script:
    - export CC=gcc-8
    - export CXX=g++-8
    - ${CXX} --version
    - cmake --version
    - export core_count=$(nproc || echo 4) && echo core_count = $core_count
    - mkdir bin
    - cd bin
    - sh: |
        if [ "$PLATFORM" = "x64" ]; then
        sudo apt-get update &&
        sudo apt-get install -y libglew-dev libegl1-mesa-dev libgles2-mesa-dev libopenal-dev libcrypto++-dev liblockfile-dev libfreeimage-dev libfreeimageplus-dev &&
        sudo apt-get install -y liblua5.1-0-dev libssl-dev libogg-dev libtheora-dev libvorbis-dev liblzo2-dev libjpeg-dev libncurses5-dev libsdl2-dev &&
        CFLAGS="-w" CXXFLAGS="-w" cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
        fi
    - sh: |
        if [ "$PLATFORM" = "x86" ]; then
        sudo dpkg --add-architecture i386 && sudo apt-get -qq update && sudo apt-get remove -y libllvm10 libgl1 libgl1-mesa-dri && sudo apt-get install -y gcc-multilib g++-8-multilib &&
        sudo apt-get install -y libglew-dev:i386 libegl1-mesa-dev:i386 libgles2-mesa-dev:i386 libopenal-dev:i386 libcrypto++-dev:i386 liblockfile-dev:i386 libfreeimage-dev:i386 libfreeimageplus-dev:i386 &&
        sudo apt-get install -y liblua5.1-0-dev:i386 libssl-dev:i386 libogg-dev:i386 libtheora-dev:i386 libvorbis-dev:i386 liblzo2-dev:i386 libjpeg-dev:i386 libncurses5-dev:i386 libsdl2-dev:i386 &&
        CFLAGS="-m32 -w" CXXFLAGS="-m32 -w" cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=i386 -DCMAKE_ASM_FLAGS=-m32
        fi
    - make -j $core_count package
    - file openxray_1.6.02_*.deb
  artifacts:
    - path: bin/openxray_1.6.02_*.deb
      name: openxray_1.6.02_*.deb

test: off

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: OpenXRay (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: kGVniXDR926BfVcA97y25BzALbijvgboBsozZzY9yc8RPz15Q4YG474h7vl14/J1
  artifact:
    OpenXRay.*.7z, Symbols.*.7z, Utils.*.7z
  draft: true
  force_update: true
